### ISSUE TITLE
Inquietud acerca de otra librería

### ISSUE THREAD

**Issue by CHANCUCO** [ycanas/LCD-PIC-LIBRARY#1]
Hola.

Muy buen trabajo relacionado con la librería de LCD para PIC16F877A.

Quisiera saber si conoce alguna librería para un sensor de color TCS3200 para el mismo PIC16F877A. Estoy trabajando en un proyecto relacionado con este sensor y no he logrado encontrar ninguna librería de ese sensor que funcione con dicho PIC. 

Muchas gracias

**Comment by ycanas** [comment]
Hola, gracias.

En realidad, no estoy familiarizado con ninguna biblioteca que pueda ser útil para ese sensor en particular, ya que nunca he tenido la oportunidad de trabajar con ese tipo de sensores.

Lamento no poder ayudarte, pero espero que puedas encontrar la información o recursos necesarios para resolver tu problema. ¡Buena suerte!

**Comment by CHANCUCO** [comment]
Ok, muchas gracias. Un saludo

**Comment by CHANCUCO** [comment]
Hola otra vez, espero estés bien.

Estoy realizando un proyecto para PIC16F877A que se basa en un sistema de seguridad de un hogar usando un sensor de movimiento PIR.

Debo de mostrar algunos mensajes en la pantalla LCD, he estado usando tu librería y tengo algunos problemas con respecto a los delays que se colocan después de mostrar un mensaje (estoy trabajando en MPLAB con XC8 compiler), no sé por qué al simularlo en Proteus cuando tengo algún un __delay_ms() mayor a 200ms, el código llega a dicha línea  y se reincia completamente, devolviendose de inmedianto al void main (void). También presento un error que cuando se cumple X condición se debe de borrar el mensaje anterior y quedarse infinitamente en el nuevo mensaje hasta que el sensor detecte algún movimiento, pero el nuevo mensaje se muestra unos segundo y despúes se empieza a mostrar el viejo mensaje (en teoría este viejo mensaje ya no debería ejecutarse). 

Si no es molestia te voy a poner el código que programé:

#include <stdio.h>
#include <stdlib.h>
#include <xc.h>
#include <pic16f877A.h>
#include <stdbool.h>
#include "LCD.h"
#define _XTAL_FREQ 4000000

#define _M1 TRISCbits.TRISC0
#define _buz TRISCbits.TRISC1
#define M1 PORTCbits.RC0 //SENSOR PIR
#define buz PORTCbits.RC1 //BUZZER
#define _E11 TRISCbits.TRISC2
#define _E12 TRISCbits.TRISC3
#define _E13 TRISCbits.TRISC4
#define _E14 TRISCbits.TRISC5
#define E11 PORTCbits.RC2 //DIPSWITCH
#define E12 PORTCbits.RC3 //DIPSWITCH
#define E13 PORTCbits.RC4 //DIPSWITCH
#define E14 PORTCbits.RC5 //DIPSWITCH

void main(void) {
    lcd_init();
    M1=1; //ENTRADA DIGITAL
    buz=0x00; //SALIDA DIGITAL
    E11=1; 
    E12=1;
    E13=1;
    E14=1;
    bool estado=false;
    bool solicitud=true;
    bool activado=false;
   
    while (1) {
        lcd_set_cursor(0,0);
        int sensor= M1;
        
        if(activado==false){
            if(estado==false){
                lcd_set_cursor(0,0);
                lcd_print("INGRESE CODIGO");
                lcd_set_cursor(1,1);
                lcd_print("DE ACTIVACION");
                __delay_ms(2000);

                if((E11==1) && (E12==0) && (E13==1) && (E14==1)){
                    lcd_clear();
                    lcd_set_cursor(0,0);
                    lcd_print("ALARMA ACTIVADA");
                    __delay_ms(3000);
                    estado=true;
                    activado=true;
                }
            }
        }
        
        if(estado==true && activado==true){
            estado=true;
            lcd_clear();
            lcd_set_cursor(0,0);
            lcd_print("DETECTANDO.....");
            __delay_ms(3000);

            if(E11==1 && E12==0 && E13==1 && E14==0){
              lcd_clear();
              lcd_set_cursor(0,0);
              lcd_print("ALARMA");
              lcd_set_cursor(0,1);
              lcd_print("DESACTIVADA");
              __delay_ms(2000);
              estado=false;
              activado=false;
            }
        }
        
        if(estado==true){
            if((PORTCbits.RC0==1) && (estado==true)){
              lcd_clear();
              lcd_set_cursor(0,0);
              lcd_print("INTRUSO");
              lcd_set_cursor(1,1);
              lcd_print("DETECTADO");
              __delay_ms(2000);

              lcd_clear();
              lcd_set_cursor(0,0);
              lcd_print("INGRESE CODIGO");
              lcd_set_cursor(1,1);
              lcd_print("PARA DESACTIVAR");
              __delay_ms(2000);


            while((estado && solicitud)==true){
              E11=PORTCbits.RC2;
              E12=PORTCbits.RC3;
              E13=PORTCbits.RC4;
              E14=PORTCbits.RC5;
              lcd_clear();

              lcd_set_cursor(0,0);
              lcd_print("POLICIA LLEGANDO");
              __delay_ms(2000);

                if(E11== 1 && E12== 0 && E13== 1 && E14== 0){
                  solicitud=false;
                  estado=false;
                  lcd_clear();
                  lcd_set_cursor(0,0);
                  lcd_print("ALARMA");
                  lcd_set_cursor(1,1);
                  lcd_print("DESACTIVADA");
                  __delay_ms(2000);
                }
            }
          solicitud=true;
          estado=false;
        }
      }
    }
}
![Captura de pantalla 2023-10-11 203722](https://github.com/ycanas/LCD-PIC16F877A/assets/147283141/799a779d-4185-4dde-b79c-978c5a7a1be3)

**Comment by ycanas** [comment]
Hola, lamento que tengas problemas. Voy a revisar la libreria en busca del problema.

**Comment by ycanas** [comment]
Después de un análisis exhaustivo y una revisión completa de la librería, creo que finalmente he llegado a la solución del problema. Únicamente se requería aumentar el retardo interno en la función de limpiar el display. He realizado múltiples pruebas y no he encontrado ningún problema. Espero que esta solución funcione para resolver tu inconveniente.

**Comment by CHANCUCO** [comment]
Muchisimas gracias.

Hice una revisión y resultó que la configuración que estaba usando para poder subir el código al Pic mediante el PICKIT3, entraba en conflicto con los delays del código. La configuración que estaba usando era:

#pragma config FOSC = XT        // Oscillator Selection bits (XT oscillator)
#pragma config WDTE = ON        // Watchdog Timer Enable bit (WDT enabled)
#pragma config PWRTE = OFF      // Power-up Timer Enable bit (PWRT disabled)
#pragma config BOREN = ON       // Brown-out Reset Enable bit (BOR enabled)
#pragma config LVP = OFF         // Low-Voltage (Single-Supply) In-Circuit Serial Programming Enable bit (RB3/PGM pin has PGM function; low-voltage programming enabled)
#pragma config CPD = OFF        // Data EEPROM Memory Code Protection bit (Data EEPROM code protection off)
#pragma config WRT = OFF        // Flash Program Memory Write Enable bits (Write protection off; all program memory may be written to by EECON control)
#pragma config CP = OFF

Cambié la configuracion a la siguiente y todo funcionó correctamente:

#pragma config FOSC = HS       // Oscillator Selection bits (HS oscillator)
#pragma config WDTE = OFF      // Watchdog Timer Enable bit (WDT disabled)
#pragma config PWRTE = ON      // Power-up Timer Enable bit (PWRT enabled)
#pragma config BOREN = OFF     // Brown-out Reset Enable bit (BOR disabled)
#pragma config LVP = OFF       // Low-Voltage (Single-Supply) In-Circuit Serial Programming Enable bit (RB3/PGM pin has PGM function; low-voltage programming disabled)
#pragma config CPD = OFF       // Data EEPROM Memory Code Protection bit (Data EEPROM code protection off)
#pragma config WRT = OFF       // Flash Program Memory Write Enable bits (Write protection off; all program memory may be written to by EECON control)
#pragma config CP = OFF        // Flash Program Memory Code Protection bit (Code protection off)

Nuevamente, muchas gracias por tu tiempo y respuestas. :)
